---

- name: Get the cluster status
  ansible.builtin.include_role:
    name: ibm_community_automation.ibm_community_automation.cluster_gather_facts_fyredev
    tasks_from: gather_cluster_status.yml
  when: not (gathered_cluster_status | default(false))

- name: Assert that the cluster exists
  ansible.builtin.assert:
    that: hostvars['cluster-facts'].cluster_hostnames | default([]) | length > 0
    msg: "{{ 'Cluster with name ' + cluster_name + ' does not exist' }}"

- name: Get the cluster details
  ansible.builtin.include_role:
    name: ibm_community_automation.ibm_community_automation.cluster_gather_facts_fyredev
    tasks_from: gather_cluster_details.yml
  when: not (gathered_cluster_details | default(false))
