---

ansible_host: localhost
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

vars_host:
  cluster_description: 'Kubernetes Cluster'
  cluster_domain: 'home.arpa'
  cluster_name: ''
  cluster_provisioner: ''
  clusters_basedir: ''
  network_cidr: ''
  http_proxy: ''
  cluster_hostnames: []
  single_node: false
  api_vip: ''
  ingress_vip: ''
  kubernetes_distro: ''
  openshift_distro: ''
  openshift_version: ''
  load_ssh_keypair: true
