---

ansible_host: localhost
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

container_run: "{{ running_in_container | default(false) | bool }}"

tasks_completed: []

vars_host:
  remote_user: ''
