---
    collections:
      - name: community.general
        source: https://galaxy.ansible.com
        version: '10.7.6'
      - name: community.aws
        source: https://galaxy.ansible.com
        version: '9.3.0'
      - name: amazon.aws
        source: https://galaxy.ansible.com
        version: '9.5.2'
      - name: google.cloud
        source: https://galaxy.ansible.com
        version: '1.3.0'
